version: '3.8'

services:
  api:
    build:
      target: development
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - ENVIRONMENT=development
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    stdin_open: true
    tty: true
    command: >
      bash -c "
      echo 'Waiting for database...' &&
      until pg_isready -h db -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-healthscore} -t 1; do
        sleep 1;
      done &&
      echo 'Running migrations...' &&
      alembic upgrade head &&
      echo 'Starting development server...' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  migrations:
    build:
      target: development
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: >
      bash -c "
      echo 'Waiting for database...' &&
      until pg_isready -h db -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-healthscore} -t 1; do
        sleep 1;
      done &&
      echo 'Running migrations...' &&
      alembic upgrade head"

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@healthscore.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
